# Generated by Django 3.2.3 on 2023-02-08 19:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiktokUserRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('global_ranking', models.IntegerField(default=0)),
                ('country_ranking', models.IntegerField(default=0)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tiktokuser')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramUserRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('global_ranking', models.IntegerField(default=0)),
                ('country_ranking', models.IntegerField(default=0)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.instagramuser')),
            ],
        ),
    ]
