# Generated by Django 3.2.3 on 2021-08-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiktokUser',
            fields=[
                ('username', models.CharField(max_length=255, unique=True)),
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('sec_uid', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('external_url', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=30)),
                ('country_full_name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('profile_pic', models.TextField()),
                ('profile_pic_hd', models.TextField()),
                ('joined_date', models.IntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('is_business_account', models.BooleanField(default=False)),
                ('followers_count', models.IntegerField()),
                ('following_count', models.IntegerField()),
                ('likes_count', models.BigIntegerField()),
                ('likes_given_count', models.IntegerField()),
                ('video_count', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
