# Generated by Django 3.2.3 on 2021-08-09 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiktokUserMedia',
            fields=[
                ('username', models.CharField(max_length=255)),
                ('create_time', models.IntegerField(default=0)),
                ('media_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('media_desc', models.TextField(blank=True)),
                ('media_duration', models.IntegerField(default=0)),
                ('media_cover_default', models.TextField(blank=True)),
                ('media_origin_cover', models.TextField(blank=True)),
                ('media_dynamic_cover', models.TextField(blank=True)),
                ('media_likes_count', models.BigIntegerField(default=0)),
                ('media_shares_count', models.BigIntegerField(default=0)),
                ('media_comments_count', models.BigIntegerField(default=0)),
                ('media_plays_count', models.BigIntegerField(default=0)),
                ('media_play_addr', models.TextField(blank=True)),
                ('media_download_addr', models.TextField(blank=True)),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tiktokuser')),
            ],
        ),
        migrations.CreateModel(
            name='TiktokUserMediaMention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention_username', models.CharField(max_length=255)),
                ('media_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medias.tiktokusermedia')),
            ],
        ),
        migrations.CreateModel(
            name='TiktokUserMediaHashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag_id', models.CharField(max_length=255)),
                ('hashtag_name', models.CharField(max_length=255)),
                ('media_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medias.tiktokusermedia')),
            ],
        ),
    ]
